### ISSUE TITLE
Automatic push to github release

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#119]
We've added automatic push to github release on ddev now, so it shouldn't be hard to do that here. It would make rolling a release a lot easier, especially at times with less bandwidth.

**Comment by mradcliffe** [comment]
Not sure if we'll run into this, but I ran into with Travis CI. There's a "limit" on attaching files via the API. I had to break releases into their Windows, Docker Tool Box, Linux and MacOS equivalents in order to successfully add the release. Otherwise it would create the release but not add the files.
