### ISSUE TITLE
Manual testing results for v1.2.0

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#150]
Here are my testing results:

* Windows 10 Pro, fairly clean system: Did start-to-finish installation
    * encountered a couple of docs issues, solved in https://github.com/drud/quicksprint/pull/149. 
    * On Windows in a virtualized environment the untar of sprint.tar.gz really does take a long time.
    * 👎 https://github.com/drud/quicksprint/issues/151
    ```
    Untarring sprint.tar.xz
    tar: ./drupal8/vendor/bin/composer: Cannot create symlink to 
    ‘../composer/composer/bin/composer’: No such file or directory
    ```
    This is a result of https://www.drupal.org/project/drupal/issues/3082866, and is a core issue. But it triggers a full-on failure when the composer build is tarred up as it is here. It's likely this issue will be resolved before Drupalcon Copenhagen, but it would sure be nice if it could be worked around here.

**Comment by mradcliffe** [comment]
I think Docker Toolbox is incompatible with VirtualBox 6 based on my testing. This should be added to a known issues list. 

Maybe a wiki page on this repository?

**Comment by rfay** [comment]
It matters a lot whether you're talking about Windows home, etc.

If you're on Win 10 Home, then Hyper-V is *not* enabled, and I think any version of Virtualbox will work. 

Please check what version of Virtualbox is bundled with Docker Toolbox. It may be latest. But again, Virtualbox doesn't play well (still) with Hyper-V.

**Comment by mradcliffe** [comment]
Docker Toolbox bundles 5.2.20 currently and trying to use VirtualBox failed when Docker Quickstart Terminal tried to bring up the VM due to an issue with the Host-only adapter.

This is Windows 10 Professional (locked down to prevent local file sharing and thus Docker Toolbox).

**Comment by rfay** [comment]
Yeah, if you're on Win 10 Pro you probably have Docker Desktop installed? Which means you have Hyper-V enabled? Which means that Virtualbox is not a good thing?

**Comment by mradcliffe** [comment]
No, I am on Windows 10 Professional, but due to Global Policy restrictions running Docker CE is not possible (file sharing disabled). This lets me test Docker Toolbox.

> Docker Toolbox bundles 5.2.20 currently and trying to use VirtualBox failed when Docker Quickstart Terminal tried to bring up the VM due to an issue with the Host-only adapter.

Some how the network driver was uninstalled. I needed to go to `C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv` and install the driver, reboot, and then the docker vm booted.

Found a separate computer-is-restricted issue:
```
$ mkcert -install                                                                                                       Created a new local CA at "C:\Users\USERNAME\AppData\Local\mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
Note: Firefox support is not available on your platform. ℹ️
```

At this point I needed to press Enter to proceed:

```
ERROR: failed to execute "keytool -importcert": exit status 1

Certificate was added to keystore
keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_102\jre\lib\security\cacerts (Access is denied)
```

There is nothing to immediately follow-up here. I am noting abnormal gotchas.

I've successfully tested 1.2.1 on MacOS High Sierra ☑️ and Windows Docker ToolBox ☑️ scenarios.

Linux is a different story, but still trying to work around non-root not being able to bind 80 on nginx despite hacking in NET_BIND_SERVICE capability into ddev (similar issue to never being able to use quicksprint/ddev as non-root).

**Comment by rfay** [comment]
Long done.
