### ISSUE TITLE
Use drupal/recommended-project for build

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#163]
drupal/recommended-project is the suggested technique for Drupal 8.8.

* It has some serious problems on WIndows
* It doesn't include drush

But we should try to figure out how to use it before next version

**Comment by mradcliffe** [comment]
Is there a drupal.org issue regarding the windows issues? I haven't seen anything pop in #composer Drupal slack channel, but I've been missing some of the composer initiative meetings lately.

**Comment by rfay** [comment]
I've only tried it once, and it was awful, every download had to restart. But I haven't returned to it. 

Where is the repo for issues on drupal/recommended-project? I am astonished that they left out drush, and more astonished that it works worse than drupal-project.

**Comment by mradcliffe** [comment]
It's a metapackage generated by drupal.org infrastructure, but all the code is in core so the core issue queue.

**Comment by mradcliffe** [comment]
Maybe I'm thinking about something else. I thought drupal/recommended-project was a metapackage from core. There might be another one.

**Comment by mradcliffe** [comment]
drupal/recommended-project _is_ committed by drupal.org infrastructure "drupal.org deployment user" on core commits. And there is a 9.0.x-dev and 8.9.x-dev on packagist. But even using that doesn't make a git repository in the web/ directory.

I think it's safer not to use a project as core development is still not composer based. This will complicate things because drush isn't installed and in order to install drush we need to change composer.json/lock in the core checkout.

**Comment by rfay** [comment]
I did some more testing on recommended-project and it fails a *lot* on WIndows (CIFS mounted filesystem). drupal-composer/drupal-project does not. So I closed the docs issue on ddev for now, https://github.com/drud/ddev/pull/1993#issuecomment-569509215

The failures are so significant on Windows that it's hard to describe them all. Right now I wouldn't want to chase that.

**Comment by rfay** [comment]
For core development it doesn't make sense to use recommended-project. Git checkout is the correct thing here. This issue didn't make any sense.
