### ISSUE TITLE
xdebug instructions

### ISSUE THREAD

**Issue by michaellenahan** [drud/quicksprint#192]
I am having trouble getting xdebug to work with ddev quicksprint.

```
➜  ~ ddev list
NAME                  TYPE     LOCATION                              URL                                          STATUS
sprint-20201209-1650  drupal9  ~/sprint/sprint-20201209-1650/drupal  https://sprint-20201209-1650.ddev.site:8443  running
DDEV ROUTER STATUS: healthy
➜  ~ cd ~/sprint/sprint-20201209-1650/drupal

➜  drupal git:(2946-255) ✗ ddev xdebug status
xdebug disabled
➜  drupal git:(2946-255) ✗ ddev xdebug on
Enabled xdebug
```

Following instructions from: https://ddev.readthedocs.io/en/stable/users/step-debugging/
PhpStorm "zero-configuration debugging" did not work, I don't get my breakpoints to hit.

Tested this by setting a breakpoint at the top of index.php, but could not get this breakpoint to hit.
```
$autoloader = require_once 'autoload.php';
```

I'm using chrome browser with the "Xdebug helper" extension, this works for me usually in my other environments.

I ended up trying the "PhpStorm "Run/Debug configuration" Debugging" instructions from https://ddev.readthedocs.io/en/stable/users/step-debugging/

Now, when I hit the debug button I get this error, because I am hitting the site using http not https:
http://sprint-20201209-1650.ddev.site:8443/?XDEBUG_SESSION_START=17541
The plain HTTP request was sent to HTTPS port, so that gives me a clue how we can fix this ...

I think the problem is something to do with the 8443 port used by quicksprint?

**Comment by michaellenahan** [comment]
![2020-12-14-112720-drud-quicksprint-issues-192-xdebug](https://user-images.githubusercontent.com/219397/102073013-f4a14b00-3e02-11eb-9c7f-3d80f4a5b4f9.png)

**Comment by rfay** [comment]
Thanks for stopping in here @michaellenahan !

I do want to make sure you know that quicksprint is really for conferences, and to go forward it would be wonderful to have you switch over to the regular ddev installation, which just gives you a long-term sustainable approach for upgrades. 

You didn't say what OS you're on, but from the screenshot it looks like macOS.

Could you please watch the video at https://ddev.com/ddev-local/ddev-local-phpstorm-and-xdebug-debugging/ and do exactly what it says there? This really does work every time. Except if you already have a "server" set up, in which case, please delete it, because then your config is already set up.

**Comment by rfay** [comment]
Closing, no response from OP. Happy to continue the conversation here or elsewhere.
