### ISSUE TITLE
Update README.md to reflect project's multiple audiences

### ISSUE THREAD

**Issue by webchick** [drud/quicksprint#24]
I think the problems I encountered (#22, #23) could both have been mitigated had the README.md on the project page been something like:

---

## For sprint mentors

blah blah stuff and things.

## For sprint attendees

blah blah other stuff and things.

---

Because from what I'm gathering, this repo is only for the people running a sprint; the "consumers" of a sprint are supposed to start from a generated tarball instead. But yet both audiences will probably find their way here, so it'd be great to direct them properly.

**Comment by rfay** [comment]
Just FYI, the README.md and package_drupal_script.sh are only for mantainers creating a release. A normal sprint user would read the SPRINTUSER_README.md, which is in the package in the release. 

Suggestions about how to make the README.md better focus on the maintainer are welcome. Note that the README is *not* included in the release, because a sprint user doesn't need to know that stuff.

**Comment by rfay** [comment]
Let's change the README.md to MAINTAINER_README.md as a first step!

**Comment by rfay** [comment]
Hoping #25 fixes your good comments @webchick  - Would appreciate your review.
